const TYPE_BET_NAP1_POTO = 'TYPE_BET_NAP1_POTO';
const TYPE_BET_NAP1_BLOQUE = 'TYPE_BET_NAP1_BLOQUE';
const TYPE_BET_NAP2 = 'TYPE_BET_NAP2';
const TYPE_BET_NAP3 = 'TYPE_BET_NAP3';
const TYPE_BET_NAP4 = 'TYPE_BET_NAP4';
const TYPE_BET_NAP5 = 'TYPE_BET_NAP5';
const TYPE_BET_TCHIGAN = 'TYPE_BET_TCHIGAN';
const TYPE_BET_PERM2 = 'TYPE_BET_PERM2';
const TYPE_BET_PERM3 = 'TYPE_BET_PERM3';

